### ISSUE TITLE
Launched a lab vm

### ISSUE THREAD

**Issue by olblak** [oufti-playground/lab-vm#13]
I run `make box` and make lab and I have an alpine vm with nothing in there.
But I have two questions
* Why did you remove the 'vagrant unsecured ssh key'?
* Which ssh key should I use?
* Is it normal that the VM doesn't contain jenkins docker images?

**Comment by dduportal** [comment]
Sorry I did not see this issue earlier. For answering you:

> Why did you remove the 'vagrant unsecured ssh key'?
What do you mean exactly? i'm not sure to get what are you referring to? (do you have a commit or PR reference?).

> Which ssh key should I use?
What is your intention? Getting into the VM? If you are using vagrant, then the command `vagrant ssh` takes care of this (cf. https://www.vagrantup.com/docs/cli/ssh.html). Or use `vagrant ssh-config` (https://www.vagrantup.com/docs/cli/ssh_config.html) to get the IP, port, key, user, etc. to do the ssh yourself: Vagrant manages this, and the private key is stored inside the ".box" folder.

> Is it normal that the VM doesn't contain jenkins docker images?
No it is not normal. I am trying to reproduce this, but it should have the services inside the box.
